#ifndef I3D_ASTEROIDDEFINES_H
#define I3D_ASTEROIDDEFINES_H

#define ASTEROID_MIN_SPEED 40
#define ASTEROID_MAX_SPEED 80
#define ASTEROID_MIN_ROTATION_SPEED 1
#define ASTEROID_MAX_ROTATION_SPEED 5
#define ASTEROID_BASE_SIZE 1
#define ASTEROID_MIN_SIZE 10
#define ASTEROID_MAX_SIZE 15
#define ASTEROID_MIN_HEALTH 1
#define ASTEROID_MAX_HEALTH 3
#define ASTEROID_RADIUS_DEVIATION 0.2 // Make sure MIN_SIZE - DEVIATION > 0!

#endif // I3D_ASTEROIDDEFINES_H