#ifndef I3D_EXHAUSTDEFINES_H
#define I3D_EXHAUSTDEFINES_H

#define MAX_EXHAUST_PARTICLES 200
#define EXHAUST_DECAY_SPEED 10
#define EXHAUST_STARTING_SIZE 10
#define EXHAUST_DROP_RATE 0.005 // seconds per particle dropped

#endif // I3D_EXHAUSTDEFINES_H